version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "jaf-adminUsers-golang"
s3_bucket = "jvb-code-lndn"
s3_prefix = "SAM/jaf-adminUsers-golang"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
# parameter_overrides = ""
image_repositories = []
